version: "3.0"
services: 
    db:
        image: mysql:5.7.19
        environment: 
            - MYSQL_DATABASE=loja
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes: 
            - /home/ubuntu/k8s-alura/volume_mysql:/var/lib/minesql
    web:
        image: gfsilveira/k8s-v1:php
        ports:
            - 8080:80
        depends_on: 
            - db
