apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-deployment
  labels:
    app: aplicacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aplicacao
  template:
    metadata:
      labels:
        app: aplicacao
    spec:
      containers:
      - name: container-aplicacao-loja
        image: gfsilveira/k8s-v1:php
        ports:
        - containerPort: 80