apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: db
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: container-mysql
          image: mysql:5.7.19
          ports:
            - containerPort: 3306 # Padrão mysql. NÃO MUDAR
          env:
            - name: MYSQL_DATABASE
              value: "loja"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1" # "1" é o mesmo que TRUE
          volumeMounts:
            - name: volume-mysql
              mountPath: /var/lib/minesql # diretório padrão dentro do mysql
      volumes:
          - name: volume-mysql
            persistentVolumeClaim:
              claimName: configuracao-mysql
